Make ZFS installation during check:tests more fail-stop.
If the exact running kernel version is not available as a package
to install, then DKMS will not be able to build the kernel package.
So we ensure that is the case during the `dnf install`.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,10 +15,15 @@ checks:tests:
   - pip3 install --user --quiet -r ci/requirements.txt
   - |
       set -e
-      echo Installing ZFS after the CI requirements so after_script codecov-wrapper does not explode if ZFS install fails.
+      # Installing ZFS after the CI requirements so after_script codecov-wrapper does not explode if ZFS install fails.
+      kver=$(uname -r)
+      echo $kver is the running kernel >&2
       sudo dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-2$(rpm --eval "%{dist}").noarch.rpm
-      echo $(uname -r) is the running kernel
-      sudo dnf install -y zfs
+      # We are now going to force the installation of the specific kernel-devel version
+      # that matches the current kernel.  If unavailable, the test should fail now.
+      # Ideally the VM image ships with a kernel-devel package that matches the
+      # booted kernel.
+      sudo dnf install -y zfs kernel-core-$kver kernel-devel-$kver
       sudo modprobe zfs
   script:
   - PYTHONPATH=test-packages:~/qubes-core-qrexec ./run-tests
